//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}acctID"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Dlr" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Int" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}MgmtCode" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}AcctDesig" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}AcctType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}RecipCode" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TaxCode" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Group" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TaxCalcFlg" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TrusteeFee" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}SrcOfFunds" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}InterestedParties" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}SystematicPlanInfo" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element name="SpousalFlg" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}LckdInCode" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}JntSurType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}JntSigType" minOccurs="0"/>
 *         &lt;element name="Estate" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Role" maxOccurs="1000"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYC-AcctID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYC-DlrAcctID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BeneOwnerCommunication" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}LeverageDislosure" minOccurs="0"/>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "acctID",
    "dlr",
    "_int",
    "mgmtCode",
    "acctDesig",
    "acctType",
    "recipCode",
    "taxCode",
    "group",
    "taxCalcFlg",
    "trusteeFee",
    "srcOfFunds",
    "interestedParties",
    "systematicPlanInfo",
    "spousalFlg",
    "lckdInCode",
    "jntSurType",
    "jntSigType",
    "estate",
    "role",
    "kycAcctID",
    "kycDlrAcctID",
    "beneOwnerCommunication",
    "leverageDislosure",
    "any"
})
@XmlRootElement(name = "Account")
public class Account {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String acctID;
    @XmlElement(name = "Dlr")
    protected Dlr dlr;
    @XmlElement(name = "Int")
    protected Int _int;
    @XmlElement(name = "MgmtCode")
    protected String mgmtCode;
    @XmlElement(name = "AcctDesig")
    protected String acctDesig;
    @XmlElement(name = "AcctType")
    protected String acctType;
    @XmlElement(name = "RecipCode")
    protected String recipCode;
    @XmlElement(name = "TaxCode")
    protected String taxCode;
    @XmlElement(name = "Group")
    protected Group group;
    @XmlElement(name = "TaxCalcFlg")
    protected TaxCalcFlg taxCalcFlg;
    @XmlElement(name = "TrusteeFee")
    protected TrusteeFee trusteeFee;
    @XmlElement(name = "SrcOfFunds")
    protected SrcOfFunds srcOfFunds;
    @XmlElement(name = "InterestedParties")
    protected InterestedParties interestedParties;
    @XmlElement(name = "SystematicPlanInfo")
    protected List<SystematicPlanInfo> systematicPlanInfo;
    @XmlElement(name = "SpousalFlg")
    protected YesType spousalFlg;
    @XmlElement(name = "LckdInCode")
    protected String lckdInCode;
    @XmlElement(name = "JntSurType")
    protected String jntSurType;
    @XmlElement(name = "JntSigType")
    protected String jntSigType;
    @XmlElement(name = "Estate")
    protected YesType estate;
    @XmlElement(name = "Role", required = true)
    protected List<Role> role;
    @XmlElement(name = "KYC-AcctID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kycAcctID;
    @XmlElement(name = "KYC-DlrAcctID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kycDlrAcctID;
    @XmlElement(name = "BeneOwnerCommunication")
    protected BeneOwnerCommunication beneOwnerCommunication;
    @XmlElement(name = "LeverageDislosure")
    protected LeverageDislosure leverageDislosure;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the acctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctID() {
        return acctID;
    }

    /**
     * Sets the value of the acctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctID(String value) {
        this.acctID = value;
    }

    /**
     * Gets the value of the dlr property.
     * 
     * @return
     *     possible object is
     *     {@link Dlr }
     *     
     */
    public Dlr getDlr() {
        return dlr;
    }

    /**
     * Sets the value of the dlr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dlr }
     *     
     */
    public void setDlr(Dlr value) {
        this.dlr = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link Int }
     *     
     */
    public Int getInt() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link Int }
     *     
     */
    public void setInt(Int value) {
        this._int = value;
    }

    /**
     * Gets the value of the mgmtCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMgmtCode() {
        return mgmtCode;
    }

    /**
     * Sets the value of the mgmtCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMgmtCode(String value) {
        this.mgmtCode = value;
    }

    /**
     * Gets the value of the acctDesig property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctDesig() {
        return acctDesig;
    }

    /**
     * Sets the value of the acctDesig property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctDesig(String value) {
        this.acctDesig = value;
    }

    /**
     * Gets the value of the acctType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctType() {
        return acctType;
    }

    /**
     * Sets the value of the acctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctType(String value) {
        this.acctType = value;
    }

    /**
     * Gets the value of the recipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipCode() {
        return recipCode;
    }

    /**
     * Sets the value of the recipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipCode(String value) {
        this.recipCode = value;
    }

    /**
     * Gets the value of the taxCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxCode() {
        return taxCode;
    }

    /**
     * Sets the value of the taxCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxCode(String value) {
        this.taxCode = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the taxCalcFlg property.
     * 
     * @return
     *     possible object is
     *     {@link TaxCalcFlg }
     *     
     */
    public TaxCalcFlg getTaxCalcFlg() {
        return taxCalcFlg;
    }

    /**
     * Sets the value of the taxCalcFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxCalcFlg }
     *     
     */
    public void setTaxCalcFlg(TaxCalcFlg value) {
        this.taxCalcFlg = value;
    }

    /**
     * Gets the value of the trusteeFee property.
     * 
     * @return
     *     possible object is
     *     {@link TrusteeFee }
     *     
     */
    public TrusteeFee getTrusteeFee() {
        return trusteeFee;
    }

    /**
     * Sets the value of the trusteeFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrusteeFee }
     *     
     */
    public void setTrusteeFee(TrusteeFee value) {
        this.trusteeFee = value;
    }

    /**
     * Gets the value of the srcOfFunds property.
     * 
     * @return
     *     possible object is
     *     {@link SrcOfFunds }
     *     
     */
    public SrcOfFunds getSrcOfFunds() {
        return srcOfFunds;
    }

    /**
     * Sets the value of the srcOfFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link SrcOfFunds }
     *     
     */
    public void setSrcOfFunds(SrcOfFunds value) {
        this.srcOfFunds = value;
    }

    /**
     * Gets the value of the interestedParties property.
     * 
     * @return
     *     possible object is
     *     {@link InterestedParties }
     *     
     */
    public InterestedParties getInterestedParties() {
        return interestedParties;
    }

    /**
     * Sets the value of the interestedParties property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterestedParties }
     *     
     */
    public void setInterestedParties(InterestedParties value) {
        this.interestedParties = value;
    }

    /**
     * Gets the value of the systematicPlanInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systematicPlanInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystematicPlanInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystematicPlanInfo }
     * 
     * 
     */
    public List<SystematicPlanInfo> getSystematicPlanInfo() {
        if (systematicPlanInfo == null) {
            systematicPlanInfo = new ArrayList<SystematicPlanInfo>();
        }
        return this.systematicPlanInfo;
    }

    /**
     * Gets the value of the spousalFlg property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getSpousalFlg() {
        return spousalFlg;
    }

    /**
     * Sets the value of the spousalFlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setSpousalFlg(YesType value) {
        this.spousalFlg = value;
    }

    /**
     * Gets the value of the lckdInCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLckdInCode() {
        return lckdInCode;
    }

    /**
     * Sets the value of the lckdInCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLckdInCode(String value) {
        this.lckdInCode = value;
    }

    /**
     * Gets the value of the jntSurType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJntSurType() {
        return jntSurType;
    }

    /**
     * Sets the value of the jntSurType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJntSurType(String value) {
        this.jntSurType = value;
    }

    /**
     * Gets the value of the jntSigType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJntSigType() {
        return jntSigType;
    }

    /**
     * Sets the value of the jntSigType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJntSigType(String value) {
        this.jntSigType = value;
    }

    /**
     * Gets the value of the estate property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getEstate() {
        return estate;
    }

    /**
     * Sets the value of the estate property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setEstate(YesType value) {
        this.estate = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the role property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Role }
     * 
     * 
     */
    public List<Role> getRole() {
        if (role == null) {
            role = new ArrayList<Role>();
        }
        return this.role;
    }

    /**
     * Gets the value of the kycAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCAcctID() {
        return kycAcctID;
    }

    /**
     * Sets the value of the kycAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCAcctID(String value) {
        this.kycAcctID = value;
    }

    /**
     * Gets the value of the kycDlrAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCDlrAcctID() {
        return kycDlrAcctID;
    }

    /**
     * Sets the value of the kycDlrAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCDlrAcctID(String value) {
        this.kycDlrAcctID = value;
    }

    /**
     * Gets the value of the beneOwnerCommunication property.
     * 
     * @return
     *     possible object is
     *     {@link BeneOwnerCommunication }
     *     
     */
    public BeneOwnerCommunication getBeneOwnerCommunication() {
        return beneOwnerCommunication;
    }

    /**
     * Sets the value of the beneOwnerCommunication property.
     * 
     * @param value
     *     allowed object is
     *     {@link BeneOwnerCommunication }
     *     
     */
    public void setBeneOwnerCommunication(BeneOwnerCommunication value) {
        this.beneOwnerCommunication = value;
    }

    /**
     * Gets the value of the leverageDislosure property.
     * 
     * @return
     *     possible object is
     *     {@link LeverageDislosure }
     *     
     */
    public LeverageDislosure getLeverageDislosure() {
        return leverageDislosure;
    }

    /**
     * Sets the value of the leverageDislosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeverageDislosure }
     *     
     */
    public void setLeverageDislosure(LeverageDislosure value) {
        this.leverageDislosure = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
