//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BankID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrBankID"/>
 *         &lt;/choice>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}CustomerID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrCustomerID"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}InstutNum" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BankName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}JntOwner" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Address" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BranchNum" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BkAcctType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BkAcctNum" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Currency" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Holder" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bankID",
    "dlrBankID",
    "customerID",
    "dlrCustomerID",
    "instutNum",
    "bankName",
    "jntOwner",
    "address",
    "branchNum",
    "bkAcctType",
    "bkAcctNum",
    "currency",
    "holder"
})
@XmlRootElement(name = "Bank")
public class Bank {

    @XmlElement(name = "BankID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bankID;
    @XmlElement(name = "DlrBankID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrBankID;
    @XmlElement(name = "CustomerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String customerID;
    @XmlElement(name = "DlrCustomerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrCustomerID;
    @XmlElement(name = "InstutNum")
    protected String instutNum;
    @XmlElement(name = "BankName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bankName;
    @XmlElement(name = "JntOwner")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String jntOwner;
    @XmlElement(name = "Address")
    protected Address address;
    @XmlElement(name = "BranchNum")
    protected String branchNum;
    @XmlElement(name = "BkAcctType")
    protected String bkAcctType;
    @XmlElement(name = "BkAcctNum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bkAcctNum;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "Holder")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String holder;

    /**
     * Gets the value of the bankID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankID() {
        return bankID;
    }

    /**
     * Sets the value of the bankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankID(String value) {
        this.bankID = value;
    }

    /**
     * Gets the value of the dlrBankID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrBankID() {
        return dlrBankID;
    }

    /**
     * Sets the value of the dlrBankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrBankID(String value) {
        this.dlrBankID = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the dlrCustomerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrCustomerID() {
        return dlrCustomerID;
    }

    /**
     * Sets the value of the dlrCustomerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrCustomerID(String value) {
        this.dlrCustomerID = value;
    }

    /**
     * Gets the value of the instutNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstutNum() {
        return instutNum;
    }

    /**
     * Sets the value of the instutNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstutNum(String value) {
        this.instutNum = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankName(String value) {
        this.bankName = value;
    }

    /**
     * Gets the value of the jntOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJntOwner() {
        return jntOwner;
    }

    /**
     * Sets the value of the jntOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJntOwner(String value) {
        this.jntOwner = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the branchNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchNum() {
        return branchNum;
    }

    /**
     * Sets the value of the branchNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchNum(String value) {
        this.branchNum = value;
    }

    /**
     * Gets the value of the bkAcctType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBkAcctType() {
        return bkAcctType;
    }

    /**
     * Sets the value of the bkAcctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBkAcctType(String value) {
        this.bkAcctType = value;
    }

    /**
     * Gets the value of the bkAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBkAcctNum() {
        return bkAcctNum;
    }

    /**
     * Sets the value of the bkAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBkAcctNum(String value) {
        this.bkAcctNum = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the holder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHolder() {
        return holder;
    }

    /**
     * Sets the value of the holder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHolder(String value) {
        this.holder = value;
    }

}
