//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BeneOwnerInfoDisclosure" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ReceiveSecurityMaterials" minOccurs="0"/>
 *         &lt;element name="SecurityMaterialElectronicyDelivery" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}LanguagePref" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "beneOwnerInfoDisclosure",
    "receiveSecurityMaterials",
    "securityMaterialElectronicyDelivery",
    "languagePref"
})
@XmlRootElement(name = "BeneOwnerCommunication")
public class BeneOwnerCommunication {

    @XmlElement(name = "BeneOwnerInfoDisclosure")
    protected String beneOwnerInfoDisclosure;
    @XmlElement(name = "ReceiveSecurityMaterials")
    protected String receiveSecurityMaterials;
    @XmlElement(name = "SecurityMaterialElectronicyDelivery")
    protected YesNoType securityMaterialElectronicyDelivery;
    @XmlElement(name = "LanguagePref")
    protected LanguageType languagePref;

    /**
     * Gets the value of the beneOwnerInfoDisclosure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeneOwnerInfoDisclosure() {
        return beneOwnerInfoDisclosure;
    }

    /**
     * Sets the value of the beneOwnerInfoDisclosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeneOwnerInfoDisclosure(String value) {
        this.beneOwnerInfoDisclosure = value;
    }

    /**
     * Gets the value of the receiveSecurityMaterials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiveSecurityMaterials() {
        return receiveSecurityMaterials;
    }

    /**
     * Sets the value of the receiveSecurityMaterials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiveSecurityMaterials(String value) {
        this.receiveSecurityMaterials = value;
    }

    /**
     * Gets the value of the securityMaterialElectronicyDelivery property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getSecurityMaterialElectronicyDelivery() {
        return securityMaterialElectronicyDelivery;
    }

    /**
     * Sets the value of the securityMaterialElectronicyDelivery property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setSecurityMaterialElectronicyDelivery(YesNoType value) {
        this.securityMaterialElectronicyDelivery = value;
    }

    /**
     * Gets the value of the languagePref property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageType }
     *     
     */
    public LanguageType getLanguagePref() {
        return languagePref;
    }

    /**
     * Sets the value of the languagePref property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *     
     */
    public void setLanguagePref(LanguageType value) {
        this.languagePref = value;
    }

}
