//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}CustomerID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrCustomerID"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}IDVerify" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ClientInfo" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}CustomerAddress" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Relation" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Employment" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}PEFP" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ForeignPerson"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ForeignEntity"/>
 *         &lt;/choice>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerID",
    "dlrCustomerID",
    "idVerify",
    "clientInfo",
    "customerAddress",
    "relation",
    "employment",
    "pefp",
    "foreignPerson",
    "foreignEntity",
    "any"
})
@XmlRootElement(name = "Customer")
public class Customer {

    @XmlElement(name = "CustomerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String customerID;
    @XmlElement(name = "DlrCustomerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrCustomerID;
    @XmlElement(name = "IDVerify")
    protected IDVerify idVerify;
    @XmlElement(name = "ClientInfo")
    protected ClientInfo clientInfo;
    @XmlElement(name = "CustomerAddress")
    protected List<CustomerAddress> customerAddress;
    @XmlElement(name = "Relation")
    protected List<Relation> relation;
    @XmlElement(name = "Employment")
    protected Employment employment;
    @XmlElement(name = "PEFP")
    protected PEFP pefp;
    @XmlElement(name = "ForeignPerson")
    protected ForeignPerson foreignPerson;
    @XmlElement(name = "ForeignEntity")
    protected ForeignEntity foreignEntity;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the dlrCustomerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrCustomerID() {
        return dlrCustomerID;
    }

    /**
     * Sets the value of the dlrCustomerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrCustomerID(String value) {
        this.dlrCustomerID = value;
    }

    /**
     * Gets the value of the idVerify property.
     * 
     * @return
     *     possible object is
     *     {@link IDVerify }
     *     
     */
    public IDVerify getIDVerify() {
        return idVerify;
    }

    /**
     * Sets the value of the idVerify property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDVerify }
     *     
     */
    public void setIDVerify(IDVerify value) {
        this.idVerify = value;
    }

    /**
     * Gets the value of the clientInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ClientInfo }
     *     
     */
    public ClientInfo getClientInfo() {
        return clientInfo;
    }

    /**
     * Sets the value of the clientInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientInfo }
     *     
     */
    public void setClientInfo(ClientInfo value) {
        this.clientInfo = value;
    }

    /**
     * Gets the value of the customerAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerAddress }
     * 
     * 
     */
    public List<CustomerAddress> getCustomerAddress() {
        if (customerAddress == null) {
            customerAddress = new ArrayList<CustomerAddress>();
        }
        return this.customerAddress;
    }

    /**
     * Gets the value of the relation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Relation }
     * 
     * 
     */
    public List<Relation> getRelation() {
        if (relation == null) {
            relation = new ArrayList<Relation>();
        }
        return this.relation;
    }

    /**
     * Gets the value of the employment property.
     * 
     * @return
     *     possible object is
     *     {@link Employment }
     *     
     */
    public Employment getEmployment() {
        return employment;
    }

    /**
     * Sets the value of the employment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employment }
     *     
     */
    public void setEmployment(Employment value) {
        this.employment = value;
    }

    /**
     * Gets the value of the pefp property.
     * 
     * @return
     *     possible object is
     *     {@link PEFP }
     *     
     */
    public PEFP getPEFP() {
        return pefp;
    }

    /**
     * Sets the value of the pefp property.
     * 
     * @param value
     *     allowed object is
     *     {@link PEFP }
     *     
     */
    public void setPEFP(PEFP value) {
        this.pefp = value;
    }

    /**
     * Gets the value of the foreignPerson property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignPerson }
     *     
     */
    public ForeignPerson getForeignPerson() {
        return foreignPerson;
    }

    /**
     * Sets the value of the foreignPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignPerson }
     *     
     */
    public void setForeignPerson(ForeignPerson value) {
        this.foreignPerson = value;
    }

    /**
     * Gets the value of the foreignEntity property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignEntity }
     *     
     */
    public ForeignEntity getForeignEntity() {
        return foreignEntity;
    }

    /**
     * Sets the value of the foreignEntity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignEntity }
     *     
     */
    public void setForeignEntity(ForeignEntity value) {
        this.foreignEntity = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
