//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrCode" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}RepCode" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrAcctID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dlrCode",
    "repCode",
    "dlrAcctID"
})
@XmlRootElement(name = "Dlr")
public class Dlr {

    @XmlElement(name = "DlrCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrCode;
    @XmlElement(name = "RepCode")
    protected String repCode;
    @XmlElement(name = "DlrAcctID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrAcctID;

    /**
     * Gets the value of the dlrCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrCode() {
        return dlrCode;
    }

    /**
     * Sets the value of the dlrCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrCode(String value) {
        this.dlrCode = value;
    }

    /**
     * Gets the value of the repCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepCode() {
        return repCode;
    }

    /**
     * Sets the value of the repCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepCode(String value) {
        this.repCode = value;
    }

    /**
     * Gets the value of the dlrAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrAcctID() {
        return dlrAcctID;
    }

    /**
     * Sets the value of the dlrAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrAcctID(String value) {
        this.dlrAcctID = value;
    }

}
