//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Country"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}EntityType"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ForeignID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}GIIN" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Date"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}RelatedParty" maxOccurs="3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "country",
    "entityType",
    "foreignID",
    "giin",
    "date",
    "relatedParty"
})
@XmlRootElement(name = "ForeignEntity")
public class ForeignEntity {

    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "EntityType", required = true)
    protected String entityType;
    @XmlElement(name = "ForeignID")
    protected ForeignID foreignID;
    @XmlElement(name = "GIIN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String giin;
    @XmlElement(name = "Date", required = true)
    protected String date;
    @XmlElement(name = "RelatedParty")
    protected List<RelatedParty> relatedParty;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntityType(String value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the foreignID property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignID }
     *     
     */
    public ForeignID getForeignID() {
        return foreignID;
    }

    /**
     * Sets the value of the foreignID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignID }
     *     
     */
    public void setForeignID(ForeignID value) {
        this.foreignID = value;
    }

    /**
     * Gets the value of the giin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGIIN() {
        return giin;
    }

    /**
     * Sets the value of the giin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGIIN(String value) {
        this.giin = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the relatedParty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedParty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedParty }
     * 
     * 
     */
    public List<RelatedParty> getRelatedParty() {
        if (relatedParty == null) {
            relatedParty = new ArrayList<RelatedParty>();
        }
        return this.relatedParty;
    }

}
