//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:19:31 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}searchRequestMetaData"/>
 *         &lt;choice>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}dlrCustomerID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}customerID"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchRequestMetaData",
    "dlrCustomerID",
    "customerID"
})
@XmlRootElement(name = "getClientDetails")
public class GetClientDetails {

    @XmlElement(required = true)
    protected SearchRequestMetaData searchRequestMetaData;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrCustomerID;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String customerID;

    /**
     * Gets the value of the searchRequestMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link SearchRequestMetaData }
     *     
     */
    public SearchRequestMetaData getSearchRequestMetaData() {
        return searchRequestMetaData;
    }

    /**
     * Sets the value of the searchRequestMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchRequestMetaData }
     *     
     */
    public void setSearchRequestMetaData(SearchRequestMetaData value) {
        this.searchRequestMetaData = value;
    }

    /**
     * Gets the value of the dlrCustomerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrCustomerID() {
        return dlrCustomerID;
    }

    /**
     * Sets the value of the dlrCustomerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrCustomerID(String value) {
        this.dlrCustomerID = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

}
