//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}IDType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}OtherDscrp" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}IDNum" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}PlaceIssue" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}VerificationQuestions" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}FirstContact" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}IRSTaxForms" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idType",
    "otherDscrp",
    "idNum",
    "placeIssue",
    "verificationQuestions",
    "firstContact",
    "irsTaxForms"
})
@XmlRootElement(name = "IDVerify")
public class IDVerify {

    @XmlElement(name = "IDType")
    protected String idType;
    @XmlElement(name = "OtherDscrp")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String otherDscrp;
    @XmlElement(name = "IDNum")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String idNum;
    @XmlElement(name = "PlaceIssue")
    protected PlaceIssue placeIssue;
    @XmlElement(name = "VerificationQuestions")
    protected VerificationQuestions verificationQuestions;
    @XmlElement(name = "FirstContact")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String firstContact;
    @XmlElement(name = "IRSTaxForms")
    protected IRSTaxForms irsTaxForms;

    /**
     * Gets the value of the idType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDType() {
        return idType;
    }

    /**
     * Sets the value of the idType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDType(String value) {
        this.idType = value;
    }

    /**
     * Gets the value of the otherDscrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherDscrp() {
        return otherDscrp;
    }

    /**
     * Sets the value of the otherDscrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherDscrp(String value) {
        this.otherDscrp = value;
    }

    /**
     * Gets the value of the idNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDNum() {
        return idNum;
    }

    /**
     * Sets the value of the idNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDNum(String value) {
        this.idNum = value;
    }

    /**
     * Gets the value of the placeIssue property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceIssue }
     *     
     */
    public PlaceIssue getPlaceIssue() {
        return placeIssue;
    }

    /**
     * Sets the value of the placeIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceIssue }
     *     
     */
    public void setPlaceIssue(PlaceIssue value) {
        this.placeIssue = value;
    }

    /**
     * Gets the value of the verificationQuestions property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationQuestions }
     *     
     */
    public VerificationQuestions getVerificationQuestions() {
        return verificationQuestions;
    }

    /**
     * Sets the value of the verificationQuestions property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationQuestions }
     *     
     */
    public void setVerificationQuestions(VerificationQuestions value) {
        this.verificationQuestions = value;
    }

    /**
     * Gets the value of the firstContact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstContact() {
        return firstContact;
    }

    /**
     * Sets the value of the firstContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstContact(String value) {
        this.firstContact = value;
    }

    /**
     * Gets the value of the irsTaxForms property.
     * 
     * @return
     *     possible object is
     *     {@link IRSTaxForms }
     *     
     */
    public IRSTaxForms getIRSTaxForms() {
        return irsTaxForms;
    }

    /**
     * Sets the value of the irsTaxForms property.
     * 
     * @param value
     *     allowed object is
     *     {@link IRSTaxForms }
     *     
     */
    public void setIRSTaxForms(IRSTaxForms value) {
        this.irsTaxForms = value;
    }

}
