//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="W-8BEN" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="W-8IMY" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="W-9" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "w8BEN",
    "w8IMY",
    "w9"
})
@XmlRootElement(name = "IRSTaxForms")
public class IRSTaxForms {

    @XmlElement(name = "W-8BEN")
    protected YesNoType w8BEN;
    @XmlElement(name = "W-8IMY")
    protected YesNoType w8IMY;
    @XmlElement(name = "W-9")
    protected YesNoType w9;

    /**
     * Gets the value of the w8BEN property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getW8BEN() {
        return w8BEN;
    }

    /**
     * Sets the value of the w8BEN property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setW8BEN(YesNoType value) {
        this.w8BEN = value;
    }

    /**
     * Gets the value of the w8IMY property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getW8IMY() {
        return w8IMY;
    }

    /**
     * Sets the value of the w8IMY property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setW8IMY(YesNoType value) {
        this.w8IMY = value;
    }

    /**
     * Gets the value of the w9 property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getW9() {
        return w9;
    }

    /**
     * Sets the value of the w9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setW9(YesNoType value) {
        this.w9 = value;
    }

}
