//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYCID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYCDlrID"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYC-Customer" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYC-Acct" maxOccurs="1000" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kycid",
    "kycDlrID",
    "kycCustomer",
    "kycAcct"
})
@XmlRootElement(name = "KYC")
public class KYC {

    @XmlElement(name = "KYCID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kycid;
    @XmlElement(name = "KYCDlrID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kycDlrID;
    @XmlElement(name = "KYC-Customer")
    protected KYCCustomer kycCustomer;
    @XmlElement(name = "KYC-Acct")
    protected List<KYCAcct> kycAcct;

    /**
     * Gets the value of the kycid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCID() {
        return kycid;
    }

    /**
     * Sets the value of the kycid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCID(String value) {
        this.kycid = value;
    }

    /**
     * Gets the value of the kycDlrID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCDlrID() {
        return kycDlrID;
    }

    /**
     * Sets the value of the kycDlrID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCDlrID(String value) {
        this.kycDlrID = value;
    }

    /**
     * Gets the value of the kycCustomer property.
     * 
     * @return
     *     possible object is
     *     {@link KYCCustomer }
     *     
     */
    public KYCCustomer getKYCCustomer() {
        return kycCustomer;
    }

    /**
     * Sets the value of the kycCustomer property.
     * 
     * @param value
     *     allowed object is
     *     {@link KYCCustomer }
     *     
     */
    public void setKYCCustomer(KYCCustomer value) {
        this.kycCustomer = value;
    }

    /**
     * Gets the value of the kycAcct property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kycAcct property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKYCAcct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KYCAcct }
     * 
     * 
     */
    public List<KYCAcct> getKYCAcct() {
        if (kycAcct == null) {
            kycAcct = new ArrayList<KYCAcct>();
        }
        return this.kycAcct;
    }

}
