//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYC-AcctID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYC-DlrAcctID"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}InvestmentObjective" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}RiskTolerance" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TimeHorizon" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}PrimaryUse" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "kycAcctID",
    "kycDlrAcctID",
    "investmentObjective",
    "riskTolerance",
    "timeHorizon",
    "primaryUse"
})
@XmlRootElement(name = "KYC-Acct")
public class KYCAcct {

    @XmlElement(name = "KYC-AcctID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kycAcctID;
    @XmlElement(name = "KYC-DlrAcctID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String kycDlrAcctID;
    @XmlElement(name = "InvestmentObjective")
    protected InvestmentObjective investmentObjective;
    @XmlElement(name = "RiskTolerance")
    protected RiskTolerance riskTolerance;
    @XmlElement(name = "TimeHorizon")
    protected String timeHorizon;
    @XmlElement(name = "PrimaryUse")
    protected String primaryUse;

    /**
     * Gets the value of the kycAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCAcctID() {
        return kycAcctID;
    }

    /**
     * Sets the value of the kycAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCAcctID(String value) {
        this.kycAcctID = value;
    }

    /**
     * Gets the value of the kycDlrAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKYCDlrAcctID() {
        return kycDlrAcctID;
    }

    /**
     * Sets the value of the kycDlrAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKYCDlrAcctID(String value) {
        this.kycDlrAcctID = value;
    }

    /**
     * Gets the value of the investmentObjective property.
     * 
     * @return
     *     possible object is
     *     {@link InvestmentObjective }
     *     
     */
    public InvestmentObjective getInvestmentObjective() {
        return investmentObjective;
    }

    /**
     * Sets the value of the investmentObjective property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestmentObjective }
     *     
     */
    public void setInvestmentObjective(InvestmentObjective value) {
        this.investmentObjective = value;
    }

    /**
     * Gets the value of the riskTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link RiskTolerance }
     *     
     */
    public RiskTolerance getRiskTolerance() {
        return riskTolerance;
    }

    /**
     * Sets the value of the riskTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link RiskTolerance }
     *     
     */
    public void setRiskTolerance(RiskTolerance value) {
        this.riskTolerance = value;
    }

    /**
     * Gets the value of the timeHorizon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeHorizon() {
        return timeHorizon;
    }

    /**
     * Sets the value of the timeHorizon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeHorizon(String value) {
        this.timeHorizon = value;
    }

    /**
     * Gets the value of the primaryUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryUse() {
        return primaryUse;
    }

    /**
     * Sets the value of the primaryUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryUse(String value) {
        this.primaryUse = value;
    }

}
