//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PreExistingLoan" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="LendingInstitution" type="{http://schemas.fundserv.com/EDOCS/edocs}string40" minOccurs="0"/>
 *         &lt;element name="LoanNumber" type="{http://schemas.fundserv.com/EDOCS/edocs}string15" minOccurs="0"/>
 *         &lt;element name="LoanType" type="{http://schemas.fundserv.com/EDOCS/edocs}string20" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}StartDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}MaturityDate" minOccurs="0"/>
 *         &lt;element name="PrincipalAmt" type="{http://schemas.fundserv.com/EDOCS/edocs}amt9v2" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Rate" minOccurs="0"/>
 *         &lt;element name="PaymentAmt" type="{http://schemas.fundserv.com/EDOCS/edocs}amt9v2" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}PaymentAmtType" minOccurs="0"/>
 *         &lt;element name="OtherInfo" type="{http://schemas.fundserv.com/EDOCS/edocs}string40" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "preExistingLoan",
    "lendingInstitution",
    "loanNumber",
    "loanType",
    "startDate",
    "maturityDate",
    "principalAmt",
    "rate",
    "paymentAmt",
    "paymentAmtType",
    "otherInfo"
})
@XmlRootElement(name = "LeverageDislosure")
public class LeverageDislosure {

    @XmlElement(name = "PreExistingLoan")
    protected YesNoType preExistingLoan;
    @XmlElement(name = "LendingInstitution")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lendingInstitution;
    @XmlElement(name = "LoanNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String loanNumber;
    @XmlElement(name = "LoanType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String loanType;
    @XmlElement(name = "StartDate")
    protected String startDate;
    @XmlElement(name = "MaturityDate")
    protected String maturityDate;
    @XmlElement(name = "PrincipalAmt")
    protected String principalAmt;
    @XmlElement(name = "Rate")
    protected String rate;
    @XmlElement(name = "PaymentAmt")
    protected String paymentAmt;
    @XmlElement(name = "PaymentAmtType")
    protected PaymentAmtType paymentAmtType;
    @XmlElement(name = "OtherInfo")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String otherInfo;

    /**
     * Gets the value of the preExistingLoan property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getPreExistingLoan() {
        return preExistingLoan;
    }

    /**
     * Sets the value of the preExistingLoan property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setPreExistingLoan(YesNoType value) {
        this.preExistingLoan = value;
    }

    /**
     * Gets the value of the lendingInstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLendingInstitution() {
        return lendingInstitution;
    }

    /**
     * Sets the value of the lendingInstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLendingInstitution(String value) {
        this.lendingInstitution = value;
    }

    /**
     * Gets the value of the loanNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanNumber() {
        return loanNumber;
    }

    /**
     * Sets the value of the loanNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanNumber(String value) {
        this.loanNumber = value;
    }

    /**
     * Gets the value of the loanType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanType() {
        return loanType;
    }

    /**
     * Sets the value of the loanType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanType(String value) {
        this.loanType = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the maturityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturityDate() {
        return maturityDate;
    }

    /**
     * Sets the value of the maturityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturityDate(String value) {
        this.maturityDate = value;
    }

    /**
     * Gets the value of the principalAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipalAmt() {
        return principalAmt;
    }

    /**
     * Sets the value of the principalAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipalAmt(String value) {
        this.principalAmt = value;
    }

    /**
     * Gets the value of the rate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRate() {
        return rate;
    }

    /**
     * Sets the value of the rate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRate(String value) {
        this.rate = value;
    }

    /**
     * Gets the value of the paymentAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAmt() {
        return paymentAmt;
    }

    /**
     * Sets the value of the paymentAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAmt(String value) {
        this.paymentAmt = value;
    }

    /**
     * Gets the value of the paymentAmtType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentAmtType }
     *     
     */
    public PaymentAmtType getPaymentAmtType() {
        return paymentAmtType;
    }

    /**
     * Sets the value of the paymentAmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentAmtType }
     *     
     */
    public void setPaymentAmtType(PaymentAmtType value) {
        this.paymentAmtType = value;
    }

    /**
     * Gets the value of the otherInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherInfo() {
        return otherInfo;
    }

    /**
     * Sets the value of the otherInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherInfo(String value) {
        this.otherInfo = value;
    }

}
