//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:49 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fundserv.schemas.edocs.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ErrorCode_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "errorCode");
    private final static QName _PolicyFault_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "policyFault");
    private final static QName _AdditionalInfo_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "additionalInfo");
    private final static QName _WorkItemId_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "workItemId");
    private final static QName _Activity_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "activity");
    private final static QName _ServiceFault_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "serviceFault");
    private final static QName _ErrorMessage_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "errorMessage");
    private final static QName _DlrCode_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "dlrCode");
    private final static QName _SrcMessageId_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "srcMessageId");
    private final static QName _NetworkId_QNAME = new QName("http://schemas.fundserv.com/EDOCS/common/", "networkId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fundserv.schemas.edocs.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PolicyFault }
     * 
     */
    public PolicyFault createPolicyFault() {
        return new PolicyFault();
    }

    /**
     * Create an instance of {@link Ping }
     * 
     */
    public Ping createPing() {
        return new Ping();
    }

    /**
     * Create an instance of {@link PingResponse }
     * 
     */
    public PingResponse createPingResponse() {
        return new PingResponse();
    }

    /**
     * Create an instance of {@link ServiceFault }
     * 
     */
    public ServiceFault createServiceFault() {
        return new ServiceFault();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "errorCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createErrorCode(String value) {
        return new JAXBElement<String>(_ErrorCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "policyFault")
    public JAXBElement<PolicyFault> createPolicyFault(PolicyFault value) {
        return new JAXBElement<PolicyFault>(_PolicyFault_QNAME, PolicyFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "additionalInfo")
    public JAXBElement<String> createAdditionalInfo(String value) {
        return new JAXBElement<String>(_AdditionalInfo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "workItemId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createWorkItemId(String value) {
        return new JAXBElement<String>(_WorkItemId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "activity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createActivity(String value) {
        return new JAXBElement<String>(_Activity_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "serviceFault")
    public JAXBElement<ServiceFault> createServiceFault(ServiceFault value) {
        return new JAXBElement<ServiceFault>(_ServiceFault_QNAME, ServiceFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "errorMessage")
    public JAXBElement<String> createErrorMessage(String value) {
        return new JAXBElement<String>(_ErrorMessage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "dlrCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDlrCode(String value) {
        return new JAXBElement<String>(_DlrCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "srcMessageId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSrcMessageId(String value) {
        return new JAXBElement<String>(_SrcMessageId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.fundserv.com/EDOCS/common/", name = "networkId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createNetworkId(String value) {
        return new JAXBElement<String>(_NetworkId_QNAME, String.class, null, value);
    }

}
