//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}OrgName" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}FedBN" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ProvBN" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}JurisdictionOfIncorp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orgName",
    "fedBN",
    "provBN",
    "jurisdictionOfIncorp"
})
@XmlRootElement(name = "Org")
public class Org {

    @XmlElement(name = "OrgName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String orgName;
    @XmlElement(name = "FedBN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fedBN;
    @XmlElement(name = "ProvBN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String provBN;
    @XmlElement(name = "JurisdictionOfIncorp")
    protected String jurisdictionOfIncorp;

    /**
     * Gets the value of the orgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * Sets the value of the orgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgName(String value) {
        this.orgName = value;
    }

    /**
     * Gets the value of the fedBN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFedBN() {
        return fedBN;
    }

    /**
     * Sets the value of the fedBN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFedBN(String value) {
        this.fedBN = value;
    }

    /**
     * Gets the value of the provBN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvBN() {
        return provBN;
    }

    /**
     * Sets the value of the provBN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvBN(String value) {
        this.provBN = value;
    }

    /**
     * Gets the value of the jurisdictionOfIncorp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJurisdictionOfIncorp() {
        return jurisdictionOfIncorp;
    }

    /**
     * Sets the value of the jurisdictionOfIncorp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJurisdictionOfIncorp(String value) {
        this.jurisdictionOfIncorp = value;
    }

}
