//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:19:31 AM MST 
//


package com.fundserv.schemas.edocs.common;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}numResults" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}pageNum" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}pageSize" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}hasNextPage" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numResults",
    "pageNum",
    "pageSize",
    "hasNextPage"
})
@XmlRootElement(name = "pagination")
public class Pagination {

    protected BigInteger numResults;
    protected BigInteger pageNum;
    protected BigInteger pageSize;
    protected YesType hasNextPage;

    /**
     * Gets the value of the numResults property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumResults() {
        return numResults;
    }

    /**
     * Sets the value of the numResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumResults(BigInteger value) {
        this.numResults = value;
    }

    /**
     * Gets the value of the pageNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPageNum() {
        return pageNum;
    }

    /**
     * Sets the value of the pageNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPageNum(BigInteger value) {
        this.pageNum = value;
    }

    /**
     * Gets the value of the pageSize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPageSize() {
        return pageSize;
    }

    /**
     * Sets the value of the pageSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPageSize(BigInteger value) {
        this.pageSize = value;
    }

    /**
     * Gets the value of the hasNextPage property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getHasNextPage() {
        return hasNextPage;
    }

    /**
     * Sets the value of the hasNextPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setHasNextPage(YesType value) {
        this.hasNextPage = value;
    }

}
