//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="InterestOnly" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType" minOccurs="0"/>
 *         &lt;element name="InterestAndPrincipal" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interestOnly",
    "interestAndPrincipal"
})
@XmlRootElement(name = "PaymentAmtType")
public class PaymentAmtType {

    @XmlElement(name = "InterestOnly")
    protected YesType interestOnly;
    @XmlElement(name = "InterestAndPrincipal")
    protected YesType interestAndPrincipal;

    /**
     * Gets the value of the interestOnly property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getInterestOnly() {
        return interestOnly;
    }

    /**
     * Sets the value of the interestOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setInterestOnly(YesType value) {
        this.interestOnly = value;
    }

    /**
     * Gets the value of the interestAndPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getInterestAndPrincipal() {
        return interestAndPrincipal;
    }

    /**
     * Sets the value of the interestAndPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setInterestAndPrincipal(YesType value) {
        this.interestAndPrincipal = value;
    }

}
