//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClientPEFP" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="RelatedtoPEFP" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}AMLcode" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://schemas.fundserv.com/EDOCS/edocs}string200" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientPEFP",
    "relatedtoPEFP",
    "amLcode",
    "comments"
})
@XmlRootElement(name = "PEFP")
public class PEFP {

    @XmlElement(name = "ClientPEFP")
    protected YesNoType clientPEFP;
    @XmlElement(name = "RelatedtoPEFP")
    protected YesNoType relatedtoPEFP;
    @XmlElement(name = "AMLcode")
    protected String amLcode;
    @XmlElement(name = "Comments")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String comments;

    /**
     * Gets the value of the clientPEFP property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getClientPEFP() {
        return clientPEFP;
    }

    /**
     * Sets the value of the clientPEFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setClientPEFP(YesNoType value) {
        this.clientPEFP = value;
    }

    /**
     * Gets the value of the relatedtoPEFP property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getRelatedtoPEFP() {
        return relatedtoPEFP;
    }

    /**
     * Sets the value of the relatedtoPEFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setRelatedtoPEFP(YesNoType value) {
        this.relatedtoPEFP = value;
    }

    /**
     * Gets the value of the amLcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMLcode() {
        return amLcode;
    }

    /**
     * Sets the value of the amLcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMLcode(String value) {
        this.amLcode = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
