//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Insider" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="CtrlGroup" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="IIROCMemberFirm" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="DlrAffiliation" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="ExistingAcctAtFirm" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="OtherFirmAcct" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://schemas.fundserv.com/EDOCS/edocs}string200" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "insider",
    "ctrlGroup",
    "iirocMemberFirm",
    "dlrAffiliation",
    "existingAcctAtFirm",
    "otherFirmAcct",
    "comments"
})
@XmlRootElement(name = "RegulatoryQuestions")
public class RegulatoryQuestions {

    @XmlElement(name = "Insider")
    protected YesNoType insider;
    @XmlElement(name = "CtrlGroup")
    protected YesNoType ctrlGroup;
    @XmlElement(name = "IIROCMemberFirm")
    protected YesNoType iirocMemberFirm;
    @XmlElement(name = "DlrAffiliation")
    protected YesNoType dlrAffiliation;
    @XmlElement(name = "ExistingAcctAtFirm")
    protected YesNoType existingAcctAtFirm;
    @XmlElement(name = "OtherFirmAcct")
    protected YesNoType otherFirmAcct;
    @XmlElement(name = "Comments")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String comments;

    /**
     * Gets the value of the insider property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getInsider() {
        return insider;
    }

    /**
     * Sets the value of the insider property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setInsider(YesNoType value) {
        this.insider = value;
    }

    /**
     * Gets the value of the ctrlGroup property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getCtrlGroup() {
        return ctrlGroup;
    }

    /**
     * Sets the value of the ctrlGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setCtrlGroup(YesNoType value) {
        this.ctrlGroup = value;
    }

    /**
     * Gets the value of the iirocMemberFirm property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getIIROCMemberFirm() {
        return iirocMemberFirm;
    }

    /**
     * Sets the value of the iirocMemberFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setIIROCMemberFirm(YesNoType value) {
        this.iirocMemberFirm = value;
    }

    /**
     * Gets the value of the dlrAffiliation property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getDlrAffiliation() {
        return dlrAffiliation;
    }

    /**
     * Sets the value of the dlrAffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setDlrAffiliation(YesNoType value) {
        this.dlrAffiliation = value;
    }

    /**
     * Gets the value of the existingAcctAtFirm property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getExistingAcctAtFirm() {
        return existingAcctAtFirm;
    }

    /**
     * Sets the value of the existingAcctAtFirm property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setExistingAcctAtFirm(YesNoType value) {
        this.existingAcctAtFirm = value;
    }

    /**
     * Gets the value of the otherFirmAcct property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getOtherFirmAcct() {
        return otherFirmAcct;
    }

    /**
     * Sets the value of the otherFirmAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setOtherFirmAcct(YesNoType value) {
        this.otherFirmAcct = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
