//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Status" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}CustomerResponse" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BankResponse" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}KYCResponse" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}acctResponse" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TrxnResponse" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}WarningError" maxOccurs="5" minOccurs="0"/>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "customerResponse",
    "bankResponse",
    "kycResponse",
    "acctResponse",
    "trxnResponse",
    "warningError",
    "any"
})
@XmlRootElement(name = "Response")
public class Response {

    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "CustomerResponse")
    protected List<CustomerResponse> customerResponse;
    @XmlElement(name = "BankResponse")
    protected List<BankResponse> bankResponse;
    @XmlElement(name = "KYCResponse")
    protected List<KYCResponse> kycResponse;
    protected List<AcctResponse> acctResponse;
    @XmlElement(name = "TrxnResponse")
    protected List<TrxnResponse> trxnResponse;
    @XmlElement(name = "WarningError")
    protected List<WarningError> warningError;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the customerResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customerResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomerResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomerResponse }
     * 
     * 
     */
    public List<CustomerResponse> getCustomerResponse() {
        if (customerResponse == null) {
            customerResponse = new ArrayList<CustomerResponse>();
        }
        return this.customerResponse;
    }

    /**
     * Gets the value of the bankResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bankResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBankResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BankResponse }
     * 
     * 
     */
    public List<BankResponse> getBankResponse() {
        if (bankResponse == null) {
            bankResponse = new ArrayList<BankResponse>();
        }
        return this.bankResponse;
    }

    /**
     * Gets the value of the kycResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kycResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKYCResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KYCResponse }
     * 
     * 
     */
    public List<KYCResponse> getKYCResponse() {
        if (kycResponse == null) {
            kycResponse = new ArrayList<KYCResponse>();
        }
        return this.kycResponse;
    }

    /**
     * Gets the value of the acctResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acctResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcctResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcctResponse }
     * 
     * 
     */
    public List<AcctResponse> getAcctResponse() {
        if (acctResponse == null) {
            acctResponse = new ArrayList<AcctResponse>();
        }
        return this.acctResponse;
    }

    /**
     * Gets the value of the trxnResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trxnResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrxnResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrxnResponse }
     * 
     * 
     */
    public List<TrxnResponse> getTrxnResponse() {
        if (trxnResponse == null) {
            trxnResponse = new ArrayList<TrxnResponse>();
        }
        return this.trxnResponse;
    }

    /**
     * Gets the value of the warningError property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warningError property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarningError().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WarningError }
     * 
     * 
     */
    public List<WarningError> getWarningError() {
        if (warningError == null) {
            warningError = new ArrayList<WarningError>();
        }
        return this.warningError;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
