//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RoleTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RoleTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Owner"/>
 *     &lt;enumeration value="Joint Owner"/>
 *     &lt;enumeration value="Spousal"/>
 *     &lt;enumeration value="ITF Beneficiary"/>
 *     &lt;enumeration value="RESP Beneficiary"/>
 *     &lt;enumeration value="Death Beneficiary"/>
 *     &lt;enumeration value="RDSP Beneficiary"/>
 *     &lt;enumeration value="TFSA Successor"/>
 *     &lt;enumeration value="Joint Annuitant"/>
 *     &lt;enumeration value="Successor Annuitant"/>
 *     &lt;enumeration value="Successor Owner"/>
 *     &lt;enumeration value="Contengient Death Beneficiary"/>
 *     &lt;enumeration value="Primary Care Giver"/>
 *     &lt;enumeration value="Beneficiary Type P-Primary"/>
 *     &lt;enumeration value="Beneficiary Type C-Contingent"/>
 *     &lt;enumeration value="Third-Party"/>
 *     &lt;enumeration value="Director"/>
 *     &lt;enumeration value="Signing-Authority"/>
 *     &lt;enumeration value="Executor"/>
 *     &lt;enumeration value="Trustee"/>
 *     &lt;enumeration value="Settlor"/>
 *     &lt;enumeration value="Agent"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RoleTypes")
@XmlEnum
public enum RoleTypes {

    @XmlEnumValue("Owner")
    OWNER("Owner"),
    @XmlEnumValue("Joint Owner")
    JOINT_OWNER("Joint Owner"),
    @XmlEnumValue("Spousal")
    SPOUSAL("Spousal"),
    @XmlEnumValue("ITF Beneficiary")
    ITF_BENEFICIARY("ITF Beneficiary"),
    @XmlEnumValue("RESP Beneficiary")
    RESP_BENEFICIARY("RESP Beneficiary"),
    @XmlEnumValue("Death Beneficiary")
    DEATH_BENEFICIARY("Death Beneficiary"),
    @XmlEnumValue("RDSP Beneficiary")
    RDSP_BENEFICIARY("RDSP Beneficiary"),
    @XmlEnumValue("TFSA Successor")
    TFSA_SUCCESSOR("TFSA Successor"),
    @XmlEnumValue("Joint Annuitant")
    JOINT_ANNUITANT("Joint Annuitant"),
    @XmlEnumValue("Successor Annuitant")
    SUCCESSOR_ANNUITANT("Successor Annuitant"),
    @XmlEnumValue("Successor Owner")
    SUCCESSOR_OWNER("Successor Owner"),
    @XmlEnumValue("Contengient Death Beneficiary")
    CONTENGIENT_DEATH_BENEFICIARY("Contengient Death Beneficiary"),
    @XmlEnumValue("Primary Care Giver")
    PRIMARY_CARE_GIVER("Primary Care Giver"),
    @XmlEnumValue("Beneficiary Type P-Primary")
    BENEFICIARY_TYPE_P_PRIMARY("Beneficiary Type P-Primary"),
    @XmlEnumValue("Beneficiary Type C-Contingent")
    BENEFICIARY_TYPE_C_CONTINGENT("Beneficiary Type C-Contingent"),
    @XmlEnumValue("Third-Party")
    THIRD_PARTY("Third-Party"),
    @XmlEnumValue("Director")
    DIRECTOR("Director"),
    @XmlEnumValue("Signing-Authority")
    SIGNING_AUTHORITY("Signing-Authority"),
    @XmlEnumValue("Executor")
    EXECUTOR("Executor"),
    @XmlEnumValue("Trustee")
    TRUSTEE("Trustee"),
    @XmlEnumValue("Settlor")
    SETTLOR("Settlor"),
    @XmlEnumValue("Agent")
    AGENT("Agent");
    private final String value;

    RoleTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoleTypes fromValue(String v) {
        for (RoleTypes c: RoleTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
