//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}CustomerID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrCustomerID"/>
 *         &lt;/choice>
 *         &lt;element name="RoleType" type="{http://schemas.fundserv.com/EDOCS/edocs}RoleTypes"/>
 *         &lt;element name="Split" type="{http://schemas.fundserv.com/EDOCS/edocs}PercentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "customerID",
    "dlrCustomerID",
    "roleType",
    "split"
})
@XmlRootElement(name = "Role")
public class Role {

    @XmlElement(name = "CustomerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String customerID;
    @XmlElement(name = "DlrCustomerID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrCustomerID;
    @XmlElement(name = "RoleType", required = true)
    protected RoleTypes roleType;
    @XmlElement(name = "Split")
    protected Float split;

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the dlrCustomerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrCustomerID() {
        return dlrCustomerID;
    }

    /**
     * Sets the value of the dlrCustomerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrCustomerID(String value) {
        this.dlrCustomerID = value;
    }

    /**
     * Gets the value of the roleType property.
     * 
     * @return
     *     possible object is
     *     {@link RoleTypes }
     *     
     */
    public RoleTypes getRoleType() {
        return roleType;
    }

    /**
     * Sets the value of the roleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleTypes }
     *     
     */
    public void setRoleType(RoleTypes value) {
        this.roleType = value;
    }

    /**
     * Gets the value of the split property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSplit() {
        return split;
    }

    /**
     * Sets the value of the split property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSplit(Float value) {
        this.split = value;
    }

}
