//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:19:31 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}searchRequestMetaData"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}pagination" minOccurs="0"/>
 *         &lt;element name="searchRequest">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}dlrCustomerID"/>
 *                   &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}dlrAcctID"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "searchRequestMetaData",
    "pagination",
    "searchRequest"
})
@XmlRootElement(name = "searchAccount")
public class SearchAccount {

    @XmlElement(required = true)
    protected SearchRequestMetaData searchRequestMetaData;
    protected Pagination pagination;
    @XmlElement(namespace = "", required = true)
    protected SearchAccount.SearchRequest searchRequest;

    /**
     * Gets the value of the searchRequestMetaData property.
     * 
     * @return
     *     possible object is
     *     {@link SearchRequestMetaData }
     *     
     */
    public SearchRequestMetaData getSearchRequestMetaData() {
        return searchRequestMetaData;
    }

    /**
     * Sets the value of the searchRequestMetaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchRequestMetaData }
     *     
     */
    public void setSearchRequestMetaData(SearchRequestMetaData value) {
        this.searchRequestMetaData = value;
    }

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the searchRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SearchAccount.SearchRequest }
     *     
     */
    public SearchAccount.SearchRequest getSearchRequest() {
        return searchRequest;
    }

    /**
     * Sets the value of the searchRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchAccount.SearchRequest }
     *     
     */
    public void setSearchRequest(SearchAccount.SearchRequest value) {
        this.searchRequest = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}dlrCustomerID"/>
     *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}dlrAcctID"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dlrCustomerID",
        "dlrAcctID"
    })
    public static class SearchRequest {

        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String dlrCustomerID;
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String dlrAcctID;

        /**
         * Gets the value of the dlrCustomerID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDlrCustomerID() {
            return dlrCustomerID;
        }

        /**
         * Sets the value of the dlrCustomerID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDlrCustomerID(String value) {
            this.dlrCustomerID = value;
        }

        /**
         * Gets the value of the dlrAcctID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDlrAcctID() {
            return dlrAcctID;
        }

        /**
         * Sets the value of the dlrAcctID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDlrAcctID(String value) {
            this.dlrAcctID = value;
        }

    }

}
