//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:19:31 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}pagination" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/EdocsInquiryService/}summarizedResult" minOccurs="0"/>
 *         &lt;element name="resultData" type="{http://schemas.fundserv.com/EDOCS/common/}stringmax"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pagination",
    "summarizedResult",
    "resultData"
})
@XmlRootElement(name = "searchAccountResponse")
public class SearchAccountResponse {

    protected Pagination pagination;
    protected YesType summarizedResult;
    @XmlElement(namespace = "", required = true)
    protected String resultData;

    /**
     * Gets the value of the pagination property.
     * 
     * @return
     *     possible object is
     *     {@link Pagination }
     *     
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Sets the value of the pagination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagination }
     *     
     */
    public void setPagination(Pagination value) {
        this.pagination = value;
    }

    /**
     * Gets the value of the summarizedResult property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getSummarizedResult() {
        return summarizedResult;
    }

    /**
     * Sets the value of the summarizedResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setSummarizedResult(YesType value) {
        this.summarizedResult = value;
    }

    /**
     * Gets the value of the resultData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultData() {
        return resultData;
    }

    /**
     * Sets the value of the resultData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultData(String value) {
        this.resultData = value;
    }

}
