//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ClientCheque" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TransferExistingAcct" minOccurs="0"/>
 *         &lt;element name="TransferExternal" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType" minOccurs="0"/>
 *         &lt;element name="DepositSecurities" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clientCheque",
    "transferExistingAcct",
    "transferExternal",
    "depositSecurities"
})
@XmlRootElement(name = "SrcOfFunds")
public class SrcOfFunds {

    @XmlElement(name = "ClientCheque")
    protected ClientCheque clientCheque;
    @XmlElement(name = "TransferExistingAcct")
    protected TransferExistingAcct transferExistingAcct;
    @XmlElement(name = "TransferExternal")
    protected YesType transferExternal;
    @XmlElement(name = "DepositSecurities")
    protected YesType depositSecurities;

    /**
     * Gets the value of the clientCheque property.
     * 
     * @return
     *     possible object is
     *     {@link ClientCheque }
     *     
     */
    public ClientCheque getClientCheque() {
        return clientCheque;
    }

    /**
     * Sets the value of the clientCheque property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClientCheque }
     *     
     */
    public void setClientCheque(ClientCheque value) {
        this.clientCheque = value;
    }

    /**
     * Gets the value of the transferExistingAcct property.
     * 
     * @return
     *     possible object is
     *     {@link TransferExistingAcct }
     *     
     */
    public TransferExistingAcct getTransferExistingAcct() {
        return transferExistingAcct;
    }

    /**
     * Sets the value of the transferExistingAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferExistingAcct }
     *     
     */
    public void setTransferExistingAcct(TransferExistingAcct value) {
        this.transferExistingAcct = value;
    }

    /**
     * Gets the value of the transferExternal property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getTransferExternal() {
        return transferExternal;
    }

    /**
     * Sets the value of the transferExternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setTransferExternal(YesType value) {
        this.transferExternal = value;
    }

    /**
     * Gets the value of the depositSecurities property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getDepositSecurities() {
        return depositSecurities;
    }

    /**
     * Sets the value of the depositSecurities property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setDepositSecurities(YesType value) {
        this.depositSecurities = value;
    }

}
