//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}SystematicPlanIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Amt" minOccurs="0"/>
 *         &lt;element name="GrossNet" type="{http://schemas.fundserv.com/EDOCS/edocs}GNCodes" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}FundID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}FrmFundID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ClientComm" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}StartDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}StopDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}RestartDate" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}RunDate" maxOccurs="1000" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Frequency" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "systematicPlanIndicator",
    "amt",
    "grossNet",
    "fundID",
    "frmFundID",
    "clientComm",
    "startDate",
    "stopDate",
    "restartDate",
    "runDate",
    "frequency"
})
@XmlRootElement(name = "SystematicPlanInfo")
public class SystematicPlanInfo {

    @XmlElement(name = "SystematicPlanIndicator")
    protected String systematicPlanIndicator;
    @XmlElement(name = "Amt")
    protected Amt amt;
    @XmlElement(name = "GrossNet")
    protected GNCodes grossNet;
    @XmlElement(name = "FundID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fundID;
    @XmlElement(name = "FrmFundID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String frmFundID;
    @XmlElement(name = "ClientComm")
    protected String clientComm;
    @XmlElement(name = "StartDate")
    protected String startDate;
    @XmlElement(name = "StopDate")
    protected String stopDate;
    @XmlElement(name = "RestartDate")
    protected String restartDate;
    @XmlElement(name = "RunDate", type = Integer.class)
    protected List<Integer> runDate;
    @XmlElement(name = "Frequency")
    protected String frequency;

    /**
     * Gets the value of the systematicPlanIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystematicPlanIndicator() {
        return systematicPlanIndicator;
    }

    /**
     * Sets the value of the systematicPlanIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystematicPlanIndicator(String value) {
        this.systematicPlanIndicator = value;
    }

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link Amt }
     *     
     */
    public Amt getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amt }
     *     
     */
    public void setAmt(Amt value) {
        this.amt = value;
    }

    /**
     * Gets the value of the grossNet property.
     * 
     * @return
     *     possible object is
     *     {@link GNCodes }
     *     
     */
    public GNCodes getGrossNet() {
        return grossNet;
    }

    /**
     * Sets the value of the grossNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link GNCodes }
     *     
     */
    public void setGrossNet(GNCodes value) {
        this.grossNet = value;
    }

    /**
     * Gets the value of the fundID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundID() {
        return fundID;
    }

    /**
     * Sets the value of the fundID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundID(String value) {
        this.fundID = value;
    }

    /**
     * Gets the value of the frmFundID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrmFundID() {
        return frmFundID;
    }

    /**
     * Sets the value of the frmFundID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrmFundID(String value) {
        this.frmFundID = value;
    }

    /**
     * Gets the value of the clientComm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientComm() {
        return clientComm;
    }

    /**
     * Sets the value of the clientComm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientComm(String value) {
        this.clientComm = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the stopDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopDate() {
        return stopDate;
    }

    /**
     * Sets the value of the stopDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopDate(String value) {
        this.stopDate = value;
    }

    /**
     * Gets the value of the restartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestartDate() {
        return restartDate;
    }

    /**
     * Sets the value of the restartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestartDate(String value) {
        this.restartDate = value;
    }

    /**
     * Gets the value of the runDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the runDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRunDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getRunDate() {
        if (runDate == null) {
            runDate = new ArrayList<Integer>();
        }
        return this.runDate;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrequency(String value) {
        this.frequency = value;
    }

}
