//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TransactionID"/>
 *         &lt;choice>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}acctID"/>
 *           &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrAcctID"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TrxnTyp"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TrxnTypDtl" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}MgmtCode"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}FrmFundID" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}FundID"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Amt"/>
 *         &lt;element name="GrossNet" type="{http://schemas.fundserv.com/EDOCS/edocs}GNCodes" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}ClientComm" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DivOpt" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}Payment" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}FrmAcct" minOccurs="0"/>
 *         &lt;any namespace='##other' minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionID",
    "acctID",
    "dlrAcctID",
    "trxnTyp",
    "trxnTypDtl",
    "mgmtCode",
    "frmFundID",
    "fundID",
    "amt",
    "grossNet",
    "clientComm",
    "divOpt",
    "payment",
    "frmAcct",
    "any"
})
@XmlRootElement(name = "Transaction")
public class Transaction {

    @XmlElement(name = "TransactionID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String transactionID;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String acctID;
    @XmlElement(name = "DlrAcctID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrAcctID;
    @XmlElement(name = "TrxnTyp", required = true)
    protected String trxnTyp;
    @XmlElement(name = "TrxnTypDtl")
    protected String trxnTypDtl;
    @XmlElement(name = "MgmtCode", required = true)
    protected String mgmtCode;
    @XmlElement(name = "FrmFundID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String frmFundID;
    @XmlElement(name = "FundID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String fundID;
    @XmlElement(name = "Amt", required = true)
    protected Amt amt;
    @XmlElement(name = "GrossNet")
    protected GNCodes grossNet;
    @XmlElement(name = "ClientComm")
    protected String clientComm;
    @XmlElement(name = "DivOpt")
    protected String divOpt;
    @XmlElement(name = "Payment")
    protected Payment payment;
    @XmlElement(name = "FrmAcct")
    protected FrmAcct frmAcct;
    @XmlAnyElement(lax = true)
    protected Object any;

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the acctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcctID() {
        return acctID;
    }

    /**
     * Sets the value of the acctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcctID(String value) {
        this.acctID = value;
    }

    /**
     * Gets the value of the dlrAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrAcctID() {
        return dlrAcctID;
    }

    /**
     * Sets the value of the dlrAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrAcctID(String value) {
        this.dlrAcctID = value;
    }

    /**
     * Gets the value of the trxnTyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrxnTyp() {
        return trxnTyp;
    }

    /**
     * Sets the value of the trxnTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrxnTyp(String value) {
        this.trxnTyp = value;
    }

    /**
     * Gets the value of the trxnTypDtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrxnTypDtl() {
        return trxnTypDtl;
    }

    /**
     * Sets the value of the trxnTypDtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrxnTypDtl(String value) {
        this.trxnTypDtl = value;
    }

    /**
     * Gets the value of the mgmtCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMgmtCode() {
        return mgmtCode;
    }

    /**
     * Sets the value of the mgmtCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMgmtCode(String value) {
        this.mgmtCode = value;
    }

    /**
     * Gets the value of the frmFundID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrmFundID() {
        return frmFundID;
    }

    /**
     * Sets the value of the frmFundID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrmFundID(String value) {
        this.frmFundID = value;
    }

    /**
     * Gets the value of the fundID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundID() {
        return fundID;
    }

    /**
     * Sets the value of the fundID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundID(String value) {
        this.fundID = value;
    }

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link Amt }
     *     
     */
    public Amt getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Amt }
     *     
     */
    public void setAmt(Amt value) {
        this.amt = value;
    }

    /**
     * Gets the value of the grossNet property.
     * 
     * @return
     *     possible object is
     *     {@link GNCodes }
     *     
     */
    public GNCodes getGrossNet() {
        return grossNet;
    }

    /**
     * Sets the value of the grossNet property.
     * 
     * @param value
     *     allowed object is
     *     {@link GNCodes }
     *     
     */
    public void setGrossNet(GNCodes value) {
        this.grossNet = value;
    }

    /**
     * Gets the value of the clientComm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientComm() {
        return clientComm;
    }

    /**
     * Sets the value of the clientComm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientComm(String value) {
        this.clientComm = value;
    }

    /**
     * Gets the value of the divOpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivOpt() {
        return divOpt;
    }

    /**
     * Sets the value of the divOpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivOpt(String value) {
        this.divOpt = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the frmAcct property.
     * 
     * @return
     *     possible object is
     *     {@link FrmAcct }
     *     
     */
    public FrmAcct getFrmAcct() {
        return frmAcct;
    }

    /**
     * Sets the value of the frmAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrmAcct }
     *     
     */
    public void setFrmAcct(FrmAcct value) {
        this.frmAcct = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAny() {
        return any;
    }

    /**
     * Sets the value of the any property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAny(Object value) {
        this.any = value;
    }

}
