//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}DlrAcctID"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TransferCash" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}TransferInKind" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dlrAcctID",
    "transferCash",
    "transferInKind"
})
@XmlRootElement(name = "TransferExistingAcct")
public class TransferExistingAcct {

    @XmlElement(name = "DlrAcctID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dlrAcctID;
    @XmlElement(name = "TransferCash")
    protected TransferCash transferCash;
    @XmlElement(name = "TransferInKind")
    protected TransferInKind transferInKind;

    /**
     * Gets the value of the dlrAcctID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlrAcctID() {
        return dlrAcctID;
    }

    /**
     * Sets the value of the dlrAcctID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlrAcctID(String value) {
        this.dlrAcctID = value;
    }

    /**
     * Gets the value of the transferCash property.
     * 
     * @return
     *     possible object is
     *     {@link TransferCash }
     *     
     */
    public TransferCash getTransferCash() {
        return transferCash;
    }

    /**
     * Sets the value of the transferCash property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferCash }
     *     
     */
    public void setTransferCash(TransferCash value) {
        this.transferCash = value;
    }

    /**
     * Gets the value of the transferInKind property.
     * 
     * @return
     *     possible object is
     *     {@link TransferInKind }
     *     
     */
    public TransferInKind getTransferInKind() {
        return transferInKind;
    }

    /**
     * Sets the value of the transferInKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransferInKind }
     *     
     */
    public void setTransferInKind(TransferInKind value) {
        this.transferInKind = value;
    }

}
