//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="deductFromAcct" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}deductFromOtherAcct"/>
 *         &lt;element ref="{http://schemas.fundserv.com/EDOCS/edocs}BankID"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deductFromAcct",
    "deductFromOtherAcct",
    "bankID"
})
@XmlRootElement(name = "TrusteeFee")
public class TrusteeFee {

    protected YesType deductFromAcct;
    protected DeductFromOtherAcct deductFromOtherAcct;
    @XmlElement(name = "BankID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String bankID;

    /**
     * Gets the value of the deductFromAcct property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getDeductFromAcct() {
        return deductFromAcct;
    }

    /**
     * Sets the value of the deductFromAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setDeductFromAcct(YesType value) {
        this.deductFromAcct = value;
    }

    /**
     * Gets the value of the deductFromOtherAcct property.
     * 
     * @return
     *     possible object is
     *     {@link DeductFromOtherAcct }
     *     
     */
    public DeductFromOtherAcct getDeductFromOtherAcct() {
        return deductFromOtherAcct;
    }

    /**
     * Sets the value of the deductFromOtherAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeductFromOtherAcct }
     *     
     */
    public void setDeductFromOtherAcct(DeductFromOtherAcct value) {
        this.deductFromOtherAcct = value;
    }

    /**
     * Gets the value of the bankID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankID() {
        return bankID;
    }

    /**
     * Sets the value of the bankID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankID(String value) {
        this.bankID = value;
    }

}
