//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 10:20:32 AM MST 
//


package com.fundserv.schemas.edocs.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StaffAcct" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="ProAcct" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="AcctHeldPEFP" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="RepLicensedInProv" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="RepMetWithClient" type="{http://schemas.fundserv.com/EDOCS/edocs}YesNoType" minOccurs="0"/>
 *         &lt;element name="DurationRepKnownClient" type="{http://schemas.fundserv.com/EDOCS/edocs}string20" minOccurs="0"/>
 *         &lt;element name="Referral" type="{http://schemas.fundserv.com/EDOCS/edocs}YesType" minOccurs="0"/>
 *         &lt;element name="ClientIdExpiryDt" type="{http://schemas.fundserv.com/EDOCS/edocs}DateType" minOccurs="0"/>
 *         &lt;element name="NameOfPersonWhoVerifiedID" type="{http://schemas.fundserv.com/EDOCS/edocs}string40" minOccurs="0"/>
 *         &lt;element name="TitleOfPersonWhoVerifiedID" type="{http://schemas.fundserv.com/EDOCS/edocs}string40" minOccurs="0"/>
 *         &lt;element name="Comments" type="{http://schemas.fundserv.com/EDOCS/edocs}string200" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "staffAcct",
    "proAcct",
    "acctHeldPEFP",
    "repLicensedInProv",
    "repMetWithClient",
    "durationRepKnownClient",
    "referral",
    "clientIdExpiryDt",
    "nameOfPersonWhoVerifiedID",
    "titleOfPersonWhoVerifiedID",
    "comments"
})
@XmlRootElement(name = "VerificationQuestions")
public class VerificationQuestions {

    @XmlElement(name = "StaffAcct")
    protected YesNoType staffAcct;
    @XmlElement(name = "ProAcct")
    protected YesNoType proAcct;
    @XmlElement(name = "AcctHeldPEFP")
    protected YesNoType acctHeldPEFP;
    @XmlElement(name = "RepLicensedInProv")
    protected YesNoType repLicensedInProv;
    @XmlElement(name = "RepMetWithClient")
    protected YesNoType repMetWithClient;
    @XmlElement(name = "DurationRepKnownClient")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String durationRepKnownClient;
    @XmlElement(name = "Referral")
    protected YesType referral;
    @XmlElement(name = "ClientIdExpiryDt")
    protected String clientIdExpiryDt;
    @XmlElement(name = "NameOfPersonWhoVerifiedID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nameOfPersonWhoVerifiedID;
    @XmlElement(name = "TitleOfPersonWhoVerifiedID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String titleOfPersonWhoVerifiedID;
    @XmlElement(name = "Comments")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String comments;

    /**
     * Gets the value of the staffAcct property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getStaffAcct() {
        return staffAcct;
    }

    /**
     * Sets the value of the staffAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setStaffAcct(YesNoType value) {
        this.staffAcct = value;
    }

    /**
     * Gets the value of the proAcct property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getProAcct() {
        return proAcct;
    }

    /**
     * Sets the value of the proAcct property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setProAcct(YesNoType value) {
        this.proAcct = value;
    }

    /**
     * Gets the value of the acctHeldPEFP property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getAcctHeldPEFP() {
        return acctHeldPEFP;
    }

    /**
     * Sets the value of the acctHeldPEFP property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setAcctHeldPEFP(YesNoType value) {
        this.acctHeldPEFP = value;
    }

    /**
     * Gets the value of the repLicensedInProv property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getRepLicensedInProv() {
        return repLicensedInProv;
    }

    /**
     * Sets the value of the repLicensedInProv property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setRepLicensedInProv(YesNoType value) {
        this.repLicensedInProv = value;
    }

    /**
     * Gets the value of the repMetWithClient property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getRepMetWithClient() {
        return repMetWithClient;
    }

    /**
     * Sets the value of the repMetWithClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setRepMetWithClient(YesNoType value) {
        this.repMetWithClient = value;
    }

    /**
     * Gets the value of the durationRepKnownClient property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDurationRepKnownClient() {
        return durationRepKnownClient;
    }

    /**
     * Sets the value of the durationRepKnownClient property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDurationRepKnownClient(String value) {
        this.durationRepKnownClient = value;
    }

    /**
     * Gets the value of the referral property.
     * 
     * @return
     *     possible object is
     *     {@link YesType }
     *     
     */
    public YesType getReferral() {
        return referral;
    }

    /**
     * Sets the value of the referral property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesType }
     *     
     */
    public void setReferral(YesType value) {
        this.referral = value;
    }

    /**
     * Gets the value of the clientIdExpiryDt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientIdExpiryDt() {
        return clientIdExpiryDt;
    }

    /**
     * Sets the value of the clientIdExpiryDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientIdExpiryDt(String value) {
        this.clientIdExpiryDt = value;
    }

    /**
     * Gets the value of the nameOfPersonWhoVerifiedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfPersonWhoVerifiedID() {
        return nameOfPersonWhoVerifiedID;
    }

    /**
     * Sets the value of the nameOfPersonWhoVerifiedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfPersonWhoVerifiedID(String value) {
        this.nameOfPersonWhoVerifiedID = value;
    }

    /**
     * Gets the value of the titleOfPersonWhoVerifiedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleOfPersonWhoVerifiedID() {
        return titleOfPersonWhoVerifiedID;
    }

    /**
     * Sets the value of the titleOfPersonWhoVerifiedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleOfPersonWhoVerifiedID(String value) {
        this.titleOfPersonWhoVerifiedID = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
